Refactor Nagios XI configurations and scripts.
Removed obsolete run configurations and unnecessary restarts in scripts. Updated MySQL permissions to support broader access, replaced hardcoded service commands with loops, and adjusted scripting for Docker compatibility. All changes aim to improve maintainability and deployment flexibility.

diff --git a/nagios_xi_src/nagiosxi/init-xidb b/nagios_xi_src/nagiosxi/init-xidb
--- a/nagios_xi_src/nagiosxi/init-xidb
+++ b/nagios_xi_src/nagiosxi/init-xidb
@@ -21,12 +21,12 @@ if [ ! -f installed.mysql ]; then
 fi
 
 echo "Checking MySQL status..."
-if service $mysqld status &>/dev/null; then
-	echo "MySQL running - continuing..."
-else
-	echo "ERROR: MySQL not running - exiting." >&2
-	exit 1
-fi
+#if service $mysqld status &>/dev/null; then
+#	echo "MySQL running - continuing..."
+#else
+#	echo "ERROR: MySQL not running - exiting." >&2
+#	exit 1
+#fi
 
 # Force mysql commands (don't die on errors)
 mysqlforce=""
@@ -42,10 +42,10 @@ sed -i "s/NAGIOSXIDEFAULTPASSWORD/$nagiosxipass/" "$proddir/html/config.inc.php"
 sed -i "s/DBMAINTDEFAULTPASSWORD/$dbmaintpass/" "nagiosxi/nagiosxi-db/nagiosxi_db.sql"
 sed -i "s/DBMAINTDEFAULTPASSWORD/$dbmaintpass/" "$proddir/html/config.inc.php"
 
-mysql -p$mysqlpass $mysqlforce < nagiosxi/nagiosxi-db/nagiosxi_db.sql > /dev/null
+mysql -u root -p$mysqlpass $mysqlforce < nagiosxi/nagiosxi-db/nagiosxi_db.sql > /dev/null
 
 echo "Loading data into database..."
-mysql -p$mysqlpass $mysqlforce < nagiosxi/nagiosxi-db/nagiosxi_db_data.sql > /dev/null
+mysql -u root -p$mysqlpass $mysqlforce < nagiosxi/nagiosxi-db/nagiosxi_db_data.sql > /dev/null
 
 echo "Nagios XI MySQL Database Initialized OK."
 touch installed.xidb
